name: PayNowStoreHook
version: '1.1'
main: gg.jos.paynowstorehook.PayNowStoreHook
api-version: '1.21'
authors: [ JosTheDude ]
description: A simple milestones system to hook in with command processors like Tebex & PayNow for spend milestone-based perks.
website: https://jos.gg/